apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-data
  namespace: livesync
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
